server:
  port: 8080
  servlet:
    context-path: /filter

spring:
  redis:
    host-name: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      maxTotal: 50
    timeout: 0
    client-type: jedis
    password:
    database: 1

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/media1.0?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

wxy:
  prop:
    # 每个接口单位时间（time）内可访问次数(max-count)
    max-count: 1
    #单位时间 ：分钟
    time: 60
    #redis key前缀
    redis-key-prefix: wxy_